#ifndef PROTOCOL_H
#define PROTOCOL_H

#include <stdint.h>

// Operation codes para Master
typedef enum {
  OP_QUERY_FILE_PATH,
  OP_QUERY_HANDSHAKE,
  OP_WORKER_HANDSHAKE_REQ,
  OP_WORKER_HANDSHAKE_RES,
} t_master_op_code;

typedef enum {
  STORAGE_OP_BLOCK_READ_REQ,
  STORAGE_OP_BLOCK_READ_RES,
  STORAGE_OP_BLOCK_WRITE_REQ,
  STORAGE_OP_BLOCK_WRITE_RES,
  STORAGE_OP_FILE_CREATE_REQ,
  STORAGE_OP_FILE_CREATE_RES,
  STORAGE_OP_FILE_TRUNCATE_REQ,
  STORAGE_OP_FILE_TRUNCATE_RES,
  STORAGE_OP_TAG_COMMIT_REQ,
  STORAGE_OP_TAG_COMMIT_RES,
  STORAGE_OP_TAG_CREATE_REQ,
  STORAGE_OP_TAG_CREATE_RES,
  STORAGE_OP_TAG_DELETE_REQ,
  STORAGE_OP_TAG_DELETE_RES,
  STORAGE_OP_WORKER_GET_BLOCK_SIZE_REQ,
  STORAGE_OP_WORKER_GET_BLOCK_SIZE_RES,
  STORAGE_OP_WORKER_SEND_ID_REQ,
  STORAGE_OP_WORKER_SEND_ID_RES,
} t_storage_op_code;

#endif
