#ifndef PROTOCOL_H
#define PROTOCOL_H

#include <stdint.h>

// Operation codes para Master
typedef enum {
    OP_WORKER_HANDSHAKE_REQ,
    OP_WORKER_HANDSHAKE_RES,
    OP_QUERY_HANDSHAKE,
    OP_QUERY_FILE_PATH,
    QC_OP_READ_DATA,
    QC_OP_MASTER_FIN_DESCONEXION,
    QC_OP_MASTER_FIN_PRIORIDAD,
    QC_OP_MASTER_CONNECTION_OK,
    OP_WORKER_ACK,
    OP_WORKER_START_QUERY,
    OP_WORKER_READ_MESSAGE_REQ,
    OP_WORKER_END_QUERY,
    OP_WORKER_PREEMPT_REQ,
    OP_WORKER_EVICT_REQ,
    OP_WORKER_EVICT_RES,
    QC_OP_DISCONNECTION,
    WORKER_OP_DISCONNECTION,
    OP_ASSIGN_QUERY,
    OP_EJECT_QUERY,
    OP_END_QUERY,
    OP_MASTER_QUERY_ERROR,
} t_master_op_code;

typedef enum {
  STORAGE_OP_BLOCK_READ_REQ,
  STORAGE_OP_BLOCK_READ_RES,
  STORAGE_OP_BLOCK_WRITE_REQ,
  STORAGE_OP_BLOCK_WRITE_RES,
  STORAGE_OP_FILE_CREATE_REQ,
  STORAGE_OP_FILE_CREATE_RES,
  STORAGE_OP_FILE_TRUNCATE_REQ,
  STORAGE_OP_FILE_TRUNCATE_RES,
  STORAGE_OP_TAG_COMMIT_REQ,
  STORAGE_OP_TAG_COMMIT_RES,
  STORAGE_OP_TAG_CREATE_REQ,
  STORAGE_OP_TAG_CREATE_RES,
  STORAGE_OP_TAG_DELETE_REQ,
  STORAGE_OP_TAG_DELETE_RES,
  STORAGE_OP_WORKER_GET_BLOCK_SIZE_REQ,
  STORAGE_OP_WORKER_GET_BLOCK_SIZE_RES,
  STORAGE_OP_WORKER_SEND_ID_REQ,
  STORAGE_OP_WORKER_SEND_ID_RES,
  STORAGE_OP_ACK,
  STORAGE_OP_ERROR,
} t_storage_op_code;

#endif
