#ifndef ERRORS_H
#define ERRORS_H
#include <stdint.h>

enum STORAGE_ERROR_CODES {
  FILE_TAG_MISSING = INT8_MIN,
  FILE_TAG_ALREADY_EXISTS,
  NOT_ENOUGH_SPACE,
  FILE_ALREADY_COMMITTED,
  READ_OUT_OF_BOUNDS
};

#endif // !ERRORS_H
