#ifndef ERRORS_H
#define ERRORS_H
#include <limits.h>

enum STORAGE_ERROR_CODES {
  FILE_TAG_MISSING = INT_MIN,
  FILE_TAG_ALREADY_EXISTS = INT_MIN + 1,
  NOT_ENOUGH_SPACE = INT_MIN + 2,
  FILE_ALREADY_COMMITTED = INT_MIN + 3,
  READ_OUT_OF_BOUNDS = INT_MIN + 4
};

#endif // !ERRORS_H
